apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc-artifacts.yaml
  - console-platform.yaml
  - agent-runtime.yaml
  - agent-worker.yaml
  - im-gateway.yaml
