from enum import StrEnum


class ErrorCode(StrEnum):
    COMMON_BAD_REQUEST = "COMMON_BAD_REQUEST"
    COMMON_VALIDATION_ERROR = "COMMON_VALIDATION_ERROR"
    COMMON_NOT_FOUND = "COMMON_NOT_FOUND"
    COMMON_CONFLICT = "COMMON_CONFLICT"
    COMMON_INTERNAL_ERROR = "COMMON_INTERNAL_ERROR"
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_DISABLED = "AGENT_DISABLED"
    AGENT_ACCESS_DENIED = "AGENT_ACCESS_DENIED"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    MODEL_DISABLED = "MODEL_DISABLED"
    SKILL_ARTIFACT_UNAVAILABLE = "SKILL_ARTIFACT_UNAVAILABLE"
    SKILL_ARTIFACT_CHECKSUM_MISMATCH = "SKILL_ARTIFACT_CHECKSUM_MISMATCH"
    MCP_DISCOVERY_FAILED = "MCP_DISCOVERY_FAILED"
