apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluxion.fullname" . }}-config
  labels:
    {{- include "fluxion.labels" . | nindent 4 }}
data:
  FLUXION_ENV: {{ .Values.env.FLUXION_ENV | default "production" | quote }}
  FLUXION_LOG_LEVEL: {{ .Values.env.FLUXION_LOG_LEVEL | default "INFO" | quote }}
