from typing import AsyncIterator, Protocol


class ChannelAdapter(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def send(self, route: dict, message: dict) -> None: ...
    async def stream(self, route: dict, events: AsyncIterator[dict]) -> None: ...
