"""V1.14 single-baseline schema (replaces the 0001-0003 chain).

Revision ID: 0001
Revises:
Create Date: 2026-09-12

V1.14 最简重设基线: the full table set is created in one revision because all
pre-V1.14 databases are dropped (see docs/05-变更记录/11-V1.13.1-to-V1.14-最简重设.md).
Net changes vs the retired chain: + execution_proposal / conversation_run /
channel_command_receipt / skill_import_preview / skill_artifact_validation_event /
skill_artifact_capability / worker_slot_counter (replaces the V1.13.1
worker_slot_lease design, ADR-056/ADR-061); + created_by / template_hash /
superseded_at / snapshot_schema_version / current_step_name / reconcile_deadline /
invocation_policy and the §3.3 attribution columns.
"""
from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UPGRADE_STATEMENTS = [
"CREATE TABLE auth_account (\n\tusername VARCHAR(128) NOT NULL, \n\tpassword_hash VARCHAR(512) NOT NULL, \n\trole VARCHAR(32) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_auth_account PRIMARY KEY (id)\n)",
'CREATE UNIQUE INDEX uq_auth_account_active_username ON auth_account (tenant_id, username) WHERE is_deleted = false',
"CREATE TABLE capability_definition (\n\tcapability_key VARCHAR(160) NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tinput_schema JSONB NOT NULL, \n\toutput_schema JSONB NOT NULL, \n\tside_effect VARCHAR(32) NOT NULL, \n\trisk_level VARCHAR(16) NOT NULL, \n\tinvocation_policy VARCHAR(16) NOT NULL, \n\tauth_requirement JSONB NOT NULL, \n\tidempotency_semantics VARCHAR(64) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_capability_definition PRIMARY KEY (id), \n\tCONSTRAINT ck_capability_definition_ck_capability_definition_side_effect CHECK (side_effect IN ('none','read','write','destructive')), \n\tCONSTRAINT ck_capability_definition_ck_capability_definition_risk_level CHECK (risk_level IN ('LOW','MEDIUM','HIGH')), \n\tCONSTRAINT ck_capability_definition_ck_capability_definition_invoc_6d38 CHECK (invocation_policy IN ('DIRECT','EXECUTION_ONLY')), \n\tCONSTRAINT ck_capability_definition_ck_capability_definition_direct_safety CHECK (invocation_policy = 'EXECUTION_ONLY' OR (side_effect IN ('none','read') AND risk_level IN ('LOW','MEDIUM')))\n)",
'CREATE UNIQUE INDEX uq_capability_definition_active_key ON capability_definition (tenant_id, capability_key) WHERE is_deleted = false',
"CREATE TABLE knowledge_source (\n\tname VARCHAR(256) NOT NULL, \n\tprovider_type VARCHAR(128) NOT NULL, \n\tconfig_ref VARCHAR(1024), \n\tmetadata JSONB NOT NULL, \n\trevision INTEGER NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_knowledge_source PRIMARY KEY (id)\n)",
'CREATE UNIQUE INDEX uq_knowledge_source_active_name ON knowledge_source (tenant_id, name) WHERE is_deleted = false',
"CREATE TABLE model_config (\n\tname VARCHAR(256) NOT NULL, \n\tprovider VARCHAR(128) NOT NULL, \n\tmodel VARCHAR(256) NOT NULL, \n\tconfig JSONB NOT NULL, \n\tapi_key_secret_ref VARCHAR(512), \n\textra_headers JSONB NOT NULL, \n\trequest_timeout_seconds INTEGER NOT NULL, \n\trevision INTEGER NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_model_config PRIMARY KEY (id)\n)",
'CREATE UNIQUE INDEX uq_model_config_active_name ON model_config (tenant_id, name) WHERE is_deleted = false',
"CREATE TABLE platform_user (\n\tuser_key VARCHAR(160) NOT NULL, \n\tdisplay_name VARCHAR(256) NOT NULL, \n\trole VARCHAR(32) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_platform_user PRIMARY KEY (id)\n)",
'CREATE UNIQUE INDEX uq_platform_user_active_key ON platform_user (tenant_id, user_key) WHERE is_deleted = false',
"CREATE TABLE project_platform (\n\tkey VARCHAR(128) NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\tauth_schema JSONB NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_project_platform PRIMARY KEY (id)\n)",
'CREATE UNIQUE INDEX uq_project_platform_active_key ON project_platform (tenant_id, key) WHERE is_deleted = false',
"CREATE TABLE skill_definition (\n\tskill_key VARCHAR(160) NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tlatest_artifact_id UUID, \n\tplatform_label VARCHAR(256) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_skill_definition PRIMARY KEY (id)\n)",
'CREATE UNIQUE INDEX uq_skill_definition_active_key ON skill_definition (tenant_id, skill_key) WHERE is_deleted = false',
"CREATE TABLE worker_slot_counter (\n\tresource_class VARCHAR(32) NOT NULL, \n\tused INTEGER NOT NULL, \n\tslot_limit INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_worker_slot_counter PRIMARY KEY (id), \n\tCONSTRAINT ck_worker_slot_counter_ck_worker_slot_counter_used_range CHECK (used >= 0 AND used <= slot_limit)\n)",
'CREATE UNIQUE INDEX uq_worker_slot_counter_resource_class ON worker_slot_counter (resource_class)',
"CREATE TABLE workspace (\n\towner_type VARCHAR(32) NOT NULL, \n\towner_id UUID NOT NULL, \n\tstorage_backend VARCHAR(64) NOT NULL, \n\troot_ref VARCHAR(1024) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_workspace PRIMARY KEY (id)\n)",
'CREATE INDEX ix_workspace_expiry ON workspace (status, expires_at)',
'CREATE UNIQUE INDEX uq_workspace_active_owner ON workspace (tenant_id, owner_type, owner_id) WHERE is_deleted = false',
"CREATE TABLE agent_definition (\n\tagent_key VARCHAR(160) NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tinstructions TEXT NOT NULL, \n\tmodel_config_id UUID, \n\tmemory_policy JSONB NOT NULL, \n\trevision INTEGER NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_agent_definition PRIMARY KEY (id), \n\tCONSTRAINT fk_agent_definition_model_config_id_model_config FOREIGN KEY(model_config_id) REFERENCES model_config (id)\n)",
'CREATE UNIQUE INDEX uq_agent_definition_active_key ON agent_definition (tenant_id, agent_key) WHERE is_deleted = false',
"CREATE TABLE audit_log (\n\tactor_user_id UUID, \n\taction VARCHAR(128) NOT NULL, \n\tresource_type VARCHAR(128) NOT NULL, \n\tresource_id VARCHAR(256) NOT NULL, \n\trequest_id VARCHAR(128), \n\ttrace_id VARCHAR(128), \n\tbefore_ref VARCHAR(1024), \n\tafter_ref VARCHAR(1024), \n\tdetails JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_audit_log PRIMARY KEY (id), \n\tCONSTRAINT fk_audit_log_actor_user_id_platform_user FOREIGN KEY(actor_user_id) REFERENCES platform_user (id)\n)",
'CREATE INDEX ix_audit_log_actor_time ON audit_log (actor_user_id, create_time)',
'CREATE INDEX ix_audit_log_entity_time ON audit_log (resource_type, resource_id, create_time)',
"CREATE TABLE auth_session (\n\taccount_id UUID NOT NULL, \n\ttoken_hash VARCHAR(128) NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_auth_session PRIMARY KEY (id), \n\tCONSTRAINT fk_auth_session_account_id_auth_account FOREIGN KEY(account_id) REFERENCES auth_account (id)\n)",
'CREATE INDEX ix_auth_session_account ON auth_session (account_id, expires_at)',
'CREATE UNIQUE INDEX uq_auth_session_token ON auth_session (token_hash)',
"CREATE TABLE capability_implementation (\n\tcapability_id UUID NOT NULL, \n\timplementation_type VARCHAR(64) NOT NULL, \n\tconfig_ref VARCHAR(1024), \n\tadapter VARCHAR(256) NOT NULL, \n\texecution_policy JSONB NOT NULL, \n\tdata_retrieval_policy JSONB, \n\trevision INTEGER NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_capability_implementation PRIMARY KEY (id), \n\tCONSTRAINT fk_capability_implementation_capability_id_capability_d_d851 FOREIGN KEY(capability_id) REFERENCES capability_definition (id)\n)",
'CREATE INDEX ix_capability_impl_lookup ON capability_implementation (capability_id, enabled, is_deleted)',
"CREATE TABLE channel_command_receipt (\n\tmessage_id UUID NOT NULL, \n\tactor_user_id UUID, \n\tcommand VARCHAR(128) NOT NULL, \n\tidempotency_key VARCHAR(256) NOT NULL, \n\trequest_digest VARCHAR(128), \n\tresult_json JSONB, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_channel_command_receipt PRIMARY KEY (id), \n\tCONSTRAINT fk_channel_command_receipt_actor_user_id_platform_user FOREIGN KEY(actor_user_id) REFERENCES platform_user (id)\n)",
'CREATE UNIQUE INDEX uq_channel_command_receipt_idempotency ON channel_command_receipt (tenant_id, idempotency_key) WHERE is_deleted = false',
'CREATE UNIQUE INDEX uq_channel_command_receipt_message ON channel_command_receipt (tenant_id, message_id) WHERE is_deleted = false',
"CREATE TABLE skill_artifact (\n\tskill_id UUID, \n\tname VARCHAR(256) NOT NULL, \n\tartifact_ref VARCHAR(1024) NOT NULL, \n\tchecksum VARCHAR(128) NOT NULL, \n\tsdk_version VARCHAR(64), \n\tentrypoint VARCHAR(256), \n\tmanifest JSONB, \n\tvalidation_status VARCHAR(32) NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_skill_artifact PRIMARY KEY (id), \n\tCONSTRAINT fk_skill_artifact_skill_id_skill_definition FOREIGN KEY(skill_id) REFERENCES skill_definition (id)\n)",
'CREATE INDEX ix_skill_artifact_name ON skill_artifact (name)',
'CREATE UNIQUE INDEX uq_skill_artifact_checksum ON skill_artifact (tenant_id, skill_id, checksum) WHERE is_deleted = false',
"CREATE TABLE skill_import_preview (\n\tskill_id UUID, \n\tartifact_ref VARCHAR(1024), \n\tmanifest_json JSONB NOT NULL, \n\tvalidation_report JSONB, \n\tpreview_token VARCHAR(256) NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tchecksum VARCHAR(128), \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_skill_import_preview PRIMARY KEY (id), \n\tCONSTRAINT fk_skill_import_preview_skill_id_skill_definition FOREIGN KEY(skill_id) REFERENCES skill_definition (id)\n)",
'CREATE UNIQUE INDEX uq_skill_import_preview_token ON skill_import_preview (tenant_id, preview_token)',
"CREATE TABLE user_memory (\n\tplatform_user_id UUID NOT NULL, \n\tmemory_key VARCHAR(256) NOT NULL, \n\tmemory_value JSONB NOT NULL, \n\tsource_type VARCHAR(64) NOT NULL, \n\tsource_ref VARCHAR(512), \n\tconfidence FLOAT NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_user_memory PRIMARY KEY (id), \n\tCONSTRAINT fk_user_memory_platform_user_id_platform_user FOREIGN KEY(platform_user_id) REFERENCES platform_user (id)\n)",
'CREATE UNIQUE INDEX uq_user_memory_active_key ON user_memory (tenant_id, platform_user_id, memory_key) WHERE is_deleted = false',
"CREATE TABLE user_project_credential (\n\tplatform_user_id UUID NOT NULL, \n\tproject_platform_id UUID NOT NULL, \n\tcredential_ref VARCHAR(512) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_user_project_credential PRIMARY KEY (id), \n\tCONSTRAINT fk_user_project_credential_platform_user_id_platform_user FOREIGN KEY(platform_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_user_project_credential_project_platform_id_project_platform FOREIGN KEY(project_platform_id) REFERENCES project_platform (id)\n)",
'CREATE UNIQUE INDEX uq_user_project_credential_active ON user_project_credential (tenant_id, platform_user_id, project_platform_id) WHERE is_deleted = false',
"CREATE TABLE agent_access_grant (\n\tplatform_user_id UUID NOT NULL, \n\tagent_id UUID NOT NULL, \n\tgranted_by UUID, \n\tenabled BOOLEAN NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_agent_access_grant PRIMARY KEY (id), \n\tCONSTRAINT fk_agent_access_grant_platform_user_id_platform_user FOREIGN KEY(platform_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_agent_access_grant_agent_id_agent_definition FOREIGN KEY(agent_id) REFERENCES agent_definition (id), \n\tCONSTRAINT fk_agent_access_grant_granted_by_platform_user FOREIGN KEY(granted_by) REFERENCES platform_user (id)\n)",
'CREATE UNIQUE INDEX uq_agent_access_grant_active ON agent_access_grant (tenant_id, platform_user_id, agent_id) WHERE is_deleted = false',
"CREATE TABLE agent_capability_binding (\n\tagent_id UUID NOT NULL, \n\tcapability_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_agent_capability_binding PRIMARY KEY (id), \n\tCONSTRAINT fk_agent_capability_binding_agent_id_agent_definition FOREIGN KEY(agent_id) REFERENCES agent_definition (id), \n\tCONSTRAINT fk_agent_capability_binding_capability_id_capability_definition FOREIGN KEY(capability_id) REFERENCES capability_definition (id)\n)",
'CREATE UNIQUE INDEX uq_agent_capability_binding_active ON agent_capability_binding (tenant_id, agent_id, capability_id) WHERE is_deleted = false',
"CREATE TABLE agent_knowledge_binding (\n\tagent_id UUID NOT NULL, \n\tknowledge_source_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_agent_knowledge_binding PRIMARY KEY (id), \n\tCONSTRAINT fk_agent_knowledge_binding_agent_id_agent_definition FOREIGN KEY(agent_id) REFERENCES agent_definition (id), \n\tCONSTRAINT fk_agent_knowledge_binding_knowledge_source_id_knowledge_source FOREIGN KEY(knowledge_source_id) REFERENCES knowledge_source (id)\n)",
'CREATE UNIQUE INDEX uq_agent_knowledge_binding_active ON agent_knowledge_binding (tenant_id, agent_id, knowledge_source_id) WHERE is_deleted = false',
"CREATE TABLE agent_skill_binding (\n\tagent_id UUID NOT NULL, \n\tskill_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_agent_skill_binding PRIMARY KEY (id), \n\tCONSTRAINT fk_agent_skill_binding_agent_id_agent_definition FOREIGN KEY(agent_id) REFERENCES agent_definition (id), \n\tCONSTRAINT fk_agent_skill_binding_skill_id_skill_definition FOREIGN KEY(skill_id) REFERENCES skill_definition (id)\n)",
'CREATE UNIQUE INDEX uq_agent_skill_binding_active ON agent_skill_binding (tenant_id, agent_id, skill_id) WHERE is_deleted = false',
"CREATE TABLE channel_account (\n\tchannel_type VARCHAR(64) NOT NULL, \n\taccount_key VARCHAR(256) NOT NULL, \n\tdefault_agent_id UUID, \n\tconfig_ref VARCHAR(512), \n\trevision INTEGER NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_channel_account PRIMARY KEY (id), \n\tCONSTRAINT fk_channel_account_default_agent_id_agent_definition FOREIGN KEY(default_agent_id) REFERENCES agent_definition (id)\n)",
'CREATE UNIQUE INDEX uq_channel_account_active ON channel_account (tenant_id, channel_type, account_key) WHERE is_deleted = false',
"CREATE TABLE conversation (\n\tplatform_user_id UUID NOT NULL, \n\tagent_id UUID, \n\tchannel_type VARCHAR(64) NOT NULL, \n\ttitle VARCHAR(256), \n\tstatus VARCHAR(32) NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_conversation PRIMARY KEY (id), \n\tCONSTRAINT fk_conversation_platform_user_id_platform_user FOREIGN KEY(platform_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_conversation_agent_id_agent_definition FOREIGN KEY(agent_id) REFERENCES agent_definition (id)\n)",
'CREATE INDEX ix_conversation_agent ON conversation (agent_id, status)',
'CREATE INDEX ix_conversation_user_time ON conversation (platform_user_id, create_time)',
"CREATE TABLE service_definition (\n\tservice_key VARCHAR(160) NOT NULL, \n\tname VARCHAR(256) NOT NULL, \n\tgoal TEXT NOT NULL, \n\tprimary_agent_id UUID, \n\texecution_type VARCHAR(32) NOT NULL, \n\tdraft_payload JSONB, \n\tcurrent_release_id UUID, \n\tstatus VARCHAR(32) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tcreated_by UUID NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_service_definition PRIMARY KEY (id), \n\tCONSTRAINT fk_service_definition_primary_agent_id_agent_definition FOREIGN KEY(primary_agent_id) REFERENCES agent_definition (id), \n\tCONSTRAINT fk_service_definition_created_by_platform_user FOREIGN KEY(created_by) REFERENCES platform_user (id)\n)",
'CREATE INDEX ix_service_definition_created_by ON service_definition (tenant_id, created_by)',
'CREATE UNIQUE INDEX uq_service_definition_active_key ON service_definition (tenant_id, service_key) WHERE is_deleted = false',
"CREATE TABLE skill_artifact_capability (\n\tskill_artifact_id UUID NOT NULL, \n\tcapability_key VARCHAR(256) NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_skill_artifact_capability PRIMARY KEY (id), \n\tCONSTRAINT fk_skill_artifact_capability_skill_artifact_id_skill_artifact FOREIGN KEY(skill_artifact_id) REFERENCES skill_artifact (id)\n)",
'CREATE UNIQUE INDEX uq_skill_artifact_capability_key ON skill_artifact_capability (tenant_id, skill_artifact_id, capability_key) WHERE is_deleted = false',
"CREATE TABLE skill_artifact_validation_event (\n\tskill_artifact_id UUID NOT NULL, \n\tresult VARCHAR(32) NOT NULL, \n\treport_ref VARCHAR(1024), \n\tcreated_by UUID, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_skill_artifact_validation_event PRIMARY KEY (id), \n\tCONSTRAINT fk_skill_artifact_validation_event_skill_artifact_id_sk_1019 FOREIGN KEY(skill_artifact_id) REFERENCES skill_artifact (id), \n\tCONSTRAINT fk_skill_artifact_validation_event_created_by_platform_user FOREIGN KEY(created_by) REFERENCES platform_user (id)\n)",
'CREATE INDEX ix_skill_artifact_validation_event_artifact ON skill_artifact_validation_event (skill_artifact_id, create_time)',
"CREATE TABLE agent_service_binding (\n\tagent_id UUID NOT NULL, \n\tservice_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_agent_service_binding PRIMARY KEY (id), \n\tCONSTRAINT fk_agent_service_binding_agent_id_agent_definition FOREIGN KEY(agent_id) REFERENCES agent_definition (id), \n\tCONSTRAINT fk_agent_service_binding_service_id_service_definition FOREIGN KEY(service_id) REFERENCES service_definition (id)\n)",
'CREATE UNIQUE INDEX uq_agent_service_binding_active ON agent_service_binding (tenant_id, agent_id, service_id) WHERE is_deleted = false',
"CREATE TABLE channel_delivery_route (\n\tplatform_user_id UUID NOT NULL, \n\tconversation_id UUID, \n\tchannel_type VARCHAR(64) NOT NULL, \n\taccount_id VARCHAR(256) NOT NULL, \n\tpeer_type VARCHAR(32) NOT NULL, \n\tpeer_id VARCHAR(512) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_channel_delivery_route PRIMARY KEY (id), \n\tCONSTRAINT fk_channel_delivery_route_platform_user_id_platform_user FOREIGN KEY(platform_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_channel_delivery_route_conversation_id_conversation FOREIGN KEY(conversation_id) REFERENCES conversation (id)\n)",
'CREATE INDEX ix_delivery_route_user_conv ON channel_delivery_route (platform_user_id, conversation_id)',
"CREATE UNIQUE INDEX uq_channel_delivery_route_active ON channel_delivery_route (tenant_id, platform_user_id, channel_type) WHERE is_deleted = false AND status = 'ACTIVE'",
"CREATE TABLE channel_identity (\n\tchannel_account_id UUID NOT NULL, \n\tidentity_scope_key VARCHAR(128) NOT NULL, \n\texternal_user_id VARCHAR(512) NOT NULL, \n\traw_identity JSONB, \n\tfirst_seen_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_channel_identity PRIMARY KEY (id), \n\tCONSTRAINT fk_channel_identity_channel_account_id_channel_account FOREIGN KEY(channel_account_id) REFERENCES channel_account (id)\n)",
'CREATE UNIQUE INDEX uq_channel_identity_active ON channel_identity (tenant_id, channel_account_id, identity_scope_key, external_user_id) WHERE is_deleted = false',
"CREATE TABLE conversation_run (\n\tconversation_id UUID NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tsource_message_id UUID, \n\tsequence_no INTEGER, \n\tlease_owner VARCHAR(256), \n\tlease_expires_at TIMESTAMP WITH TIME ZONE, \n\tlease_epoch BIGINT NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_conversation_run PRIMARY KEY (id), \n\tCONSTRAINT fk_conversation_run_conversation_id_conversation FOREIGN KEY(conversation_id) REFERENCES conversation (id)\n)",
'CREATE INDEX ix_conversation_run_conversation_seq ON conversation_run (tenant_id, conversation_id, sequence_no)',
"CREATE TABLE message (\n\tconversation_id UUID NOT NULL, \n\trole VARCHAR(32) NOT NULL, \n\tcontent_ref VARCHAR(1024), \n\tcontent JSONB, \n\texternal_message_id VARCHAR(512), \n\tverified_channel_account_id UUID, \n\tactor_user_id UUID, \n\tprocessing_status VARCHAR(32) NOT NULL, \n\tsequence_no INTEGER, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_message PRIMARY KEY (id), \n\tCONSTRAINT fk_message_conversation_id_conversation FOREIGN KEY(conversation_id) REFERENCES conversation (id), \n\tCONSTRAINT fk_message_verified_channel_account_id_channel_account FOREIGN KEY(verified_channel_account_id) REFERENCES channel_account (id), \n\tCONSTRAINT fk_message_actor_user_id_platform_user FOREIGN KEY(actor_user_id) REFERENCES platform_user (id)\n)",
'CREATE INDEX ix_message_conversation_time ON message (conversation_id, create_time)',
'CREATE UNIQUE INDEX uq_message_external ON message (tenant_id, external_message_id)',
"CREATE TABLE service_release (\n\tservice_id UUID NOT NULL, \n\trelease_no VARCHAR(128) NOT NULL, \n\tcontent_hash VARCHAR(128) NOT NULL, \n\tpublished_payload JSONB NOT NULL, \n\tpublished_by UUID, \n\tpublished_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_service_release PRIMARY KEY (id), \n\tCONSTRAINT fk_service_release_service_id_service_definition FOREIGN KEY(service_id) REFERENCES service_definition (id), \n\tCONSTRAINT fk_service_release_published_by_platform_user FOREIGN KEY(published_by) REFERENCES platform_user (id)\n)",
'CREATE UNIQUE INDEX uq_service_release_hash ON service_release (tenant_id, service_id, content_hash) WHERE is_deleted = false',
'CREATE UNIQUE INDEX uq_service_release_no ON service_release (tenant_id, service_id, release_no) WHERE is_deleted = false',
"CREATE TABLE bind_code (\n\tplatform_user_id UUID NOT NULL, \n\tchannel_type VARCHAR(64) NOT NULL, \n\tcode_hash VARCHAR(128) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tused_identity_id UUID, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tused_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_bind_code PRIMARY KEY (id), \n\tCONSTRAINT fk_bind_code_platform_user_id_platform_user FOREIGN KEY(platform_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_bind_code_used_identity_id_channel_identity FOREIGN KEY(used_identity_id) REFERENCES channel_identity (id)\n)",
'CREATE UNIQUE INDEX uq_bind_code_hash ON bind_code (tenant_id, code_hash)',
"CREATE UNIQUE INDEX uq_bind_code_single_pending ON bind_code (tenant_id, platform_user_id, channel_type) WHERE is_deleted = false AND status = 'PENDING'",
"CREATE TABLE channel_binding (\n\tplatform_user_id UUID NOT NULL, \n\tchannel_identity_id UUID NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tbound_at TIMESTAMP WITH TIME ZONE, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_channel_binding PRIMARY KEY (id), \n\tCONSTRAINT fk_channel_binding_platform_user_id_platform_user FOREIGN KEY(platform_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_channel_binding_channel_identity_id_channel_identity FOREIGN KEY(channel_identity_id) REFERENCES channel_identity (id)\n)",
"CREATE UNIQUE INDEX uq_channel_binding_active_identity ON channel_binding (channel_identity_id) WHERE is_deleted = false AND status = 'ACTIVE'",
"CREATE TABLE execution_snapshot (\n\tservice_release_id UUID, \n\tservice_release_ref VARCHAR(256) NOT NULL, \n\tservice_content_hash VARCHAR(128) NOT NULL, \n\tagent_release_ref VARCHAR(256), \n\tagent_revision INTEGER, \n\tsnapshot_schema_version INTEGER DEFAULT 1 NOT NULL, \n\tsnapshot_payload JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_execution_snapshot PRIMARY KEY (id), \n\tCONSTRAINT fk_execution_snapshot_service_release_id_service_release FOREIGN KEY(service_release_id) REFERENCES service_release (id)\n)",
'CREATE UNIQUE INDEX uq_execution_snapshot_hash ON execution_snapshot (tenant_id, service_release_id, service_content_hash) WHERE is_deleted = false',
"CREATE TABLE service_execution (\n\tservice_id UUID, \n\tservice_release_id UUID, \n\tactor_user_id UUID NOT NULL, \n\tprimary_agent_id UUID, \n\tconversation_id UUID, \n\tdelivery_route_id UUID, \n\tsnapshot_id UUID NOT NULL, \n\tworkspace_id UUID, \n\tservice_release_ref VARCHAR(256) NOT NULL, \n\tresource_scope JSONB NOT NULL, \n\tinput JSONB NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tcurrent_step VARCHAR(256), \n\tcurrent_step_name VARCHAR(128), \n\tnext_run_at TIMESTAMP WITH TIME ZONE, \n\tlease_owner VARCHAR(256), \n\tlease_expires_at TIMESTAMP WITH TIME ZONE, \n\tattempt INTEGER NOT NULL, \n\tmax_attempts INTEGER NOT NULL, \n\tidempotency_key VARCHAR(512) NOT NULL, \n\ttrace_id VARCHAR(128), \n\tchannel_source VARCHAR(32), \n\twaiting_reason VARCHAR(256), \n\thuman_deadline TIMESTAMP WITH TIME ZONE, \n\trequested_action VARCHAR(16), \n\tretry_count INTEGER NOT NULL, \n\tpriority INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_service_execution PRIMARY KEY (id), \n\tCONSTRAINT fk_service_execution_service_id_service_definition FOREIGN KEY(service_id) REFERENCES service_definition (id), \n\tCONSTRAINT fk_service_execution_service_release_id_service_release FOREIGN KEY(service_release_id) REFERENCES service_release (id), \n\tCONSTRAINT fk_service_execution_actor_user_id_platform_user FOREIGN KEY(actor_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_service_execution_primary_agent_id_agent_definition FOREIGN KEY(primary_agent_id) REFERENCES agent_definition (id), \n\tCONSTRAINT fk_service_execution_conversation_id_conversation FOREIGN KEY(conversation_id) REFERENCES conversation (id), \n\tCONSTRAINT fk_service_execution_delivery_route_id_channel_delivery_route FOREIGN KEY(delivery_route_id) REFERENCES channel_delivery_route (id), \n\tCONSTRAINT fk_service_execution_snapshot_id_execution_snapshot FOREIGN KEY(snapshot_id) REFERENCES execution_snapshot (id), \n\tCONSTRAINT fk_service_execution_workspace_id_workspace FOREIGN KEY(workspace_id) REFERENCES workspace (id)\n)",
'CREATE INDEX ix_service_execution_actor_time ON service_execution (actor_user_id, create_time)',
'CREATE INDEX ix_service_execution_due ON service_execution (status, next_run_at)',
'CREATE INDEX ix_service_execution_lease ON service_execution (status, lease_expires_at)',
'CREATE INDEX ix_service_execution_trace ON service_execution (trace_id)',
'CREATE UNIQUE INDEX uq_service_execution_active_idempotency ON service_execution (tenant_id, idempotency_key) WHERE is_deleted = false',
"CREATE TABLE execution_command (\n\texecution_id UUID NOT NULL, \n\tactor_user_id UUID, \n\tcommand_type VARCHAR(64) NOT NULL, \n\tpayload JSONB NOT NULL, \n\tidempotency_key VARCHAR(512), \n\trequest_digest VARCHAR(128), \n\taccepted_at TIMESTAMP WITH TIME ZONE, \n\tresult_execution_id UUID, \n\tstatus VARCHAR(32) NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_execution_command PRIMARY KEY (id), \n\tCONSTRAINT fk_execution_command_execution_id_service_execution FOREIGN KEY(execution_id) REFERENCES service_execution (id), \n\tCONSTRAINT fk_execution_command_actor_user_id_platform_user FOREIGN KEY(actor_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_execution_command_result_execution_id_service_execution FOREIGN KEY(result_execution_id) REFERENCES service_execution (id)\n)",
'CREATE INDEX ix_execution_command_execution_status ON execution_command (execution_id, status)',
'CREATE UNIQUE INDEX uq_execution_command_active_idempotency ON execution_command (tenant_id, idempotency_key) WHERE is_deleted = false AND idempotency_key IS NOT NULL',
"CREATE TABLE execution_proposal (\n\tactor_user_id UUID NOT NULL, \n\tconversation_id UUID NOT NULL, \n\tservice_id UUID NOT NULL, \n\tagent_id UUID NOT NULL, \n\tservice_release_id UUID NOT NULL, \n\tsnapshot_id UUID NOT NULL, \n\tinput_json JSONB NOT NULL, \n\tresource_scope_json JSONB NOT NULL, \n\ttemplate_hash VARCHAR(64) NOT NULL, \n\tconfirmation_digest VARCHAR(64) NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\tsuperseded_at TIMESTAMP WITH TIME ZONE, \n\tconfirmed_message_id UUID, \n\tconfirmed_at TIMESTAMP WITH TIME ZONE, \n\texecution_id UUID, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_execution_proposal PRIMARY KEY (id), \n\tCONSTRAINT ck_execution_proposal_ck_execution_proposal_confirmed_fields CHECK ((status = 'CONFIRMED' AND confirmed_message_id IS NOT NULL AND confirmed_at IS NOT NULL AND execution_id IS NOT NULL) OR (status != 'CONFIRMED' AND confirmed_message_id IS NULL AND confirmed_at IS NULL AND execution_id IS NULL)), \n\tCONSTRAINT fk_execution_proposal_actor_user_id_platform_user FOREIGN KEY(actor_user_id) REFERENCES platform_user (id), \n\tCONSTRAINT fk_execution_proposal_conversation_id_conversation FOREIGN KEY(conversation_id) REFERENCES conversation (id), \n\tCONSTRAINT fk_execution_proposal_service_id_service_definition FOREIGN KEY(service_id) REFERENCES service_definition (id), \n\tCONSTRAINT fk_execution_proposal_agent_id_agent_definition FOREIGN KEY(agent_id) REFERENCES agent_definition (id), \n\tCONSTRAINT fk_execution_proposal_service_release_id_service_release FOREIGN KEY(service_release_id) REFERENCES service_release (id), \n\tCONSTRAINT fk_execution_proposal_snapshot_id_execution_snapshot FOREIGN KEY(snapshot_id) REFERENCES execution_snapshot (id), \n\tCONSTRAINT fk_execution_proposal_confirmed_message_id_message FOREIGN KEY(confirmed_message_id) REFERENCES message (id), \n\tCONSTRAINT fk_execution_proposal_execution_id_service_execution FOREIGN KEY(execution_id) REFERENCES service_execution (id)\n)",
"CREATE UNIQUE INDEX uq_execution_proposal_pending_conversation ON execution_proposal (tenant_id, conversation_id) WHERE is_deleted = false AND status = 'PENDING'",
"CREATE TABLE execution_step (\n\texecution_id UUID NOT NULL, \n\tstep_key VARCHAR(256) NOT NULL, \n\tstep_type VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tattempt INTEGER NOT NULL, \n\tidempotency_key VARCHAR(512), \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tresult JSONB, \n\terror JSONB, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_execution_step PRIMARY KEY (id), \n\tCONSTRAINT fk_execution_step_execution_id_service_execution FOREIGN KEY(execution_id) REFERENCES service_execution (id)\n)",
'CREATE INDEX ix_execution_step_execution_status ON execution_step (execution_id, status)',
'CREATE UNIQUE INDEX uq_execution_step_active ON execution_step (tenant_id, execution_id, step_key) WHERE is_deleted = false',
"CREATE TABLE task_progress_event (\n\texecution_id UUID NOT NULL, \n\tevent_type VARCHAR(64) NOT NULL, \n\tstage VARCHAR(256), \n\tprogress INTEGER, \n\tvisibility VARCHAR(32) NOT NULL, \n\tpayload JSONB NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_task_progress_event PRIMARY KEY (id), \n\tCONSTRAINT fk_task_progress_event_execution_id_service_execution FOREIGN KEY(execution_id) REFERENCES service_execution (id)\n)",
'CREATE INDEX ix_progress_event_execution_time ON task_progress_event (execution_id, occurred_at)',
"CREATE TABLE artifact (\n\towner_type VARCHAR(64), \n\towner_id UUID, \n\tworkspace_id UUID, \n\texecution_id UUID NOT NULL, \n\texecution_step_id UUID, \n\tartifact_type VARCHAR(64) NOT NULL, \n\tobject_ref VARCHAR(1024) NOT NULL, \n\tchecksum VARCHAR(128), \n\tmetadata JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_artifact PRIMARY KEY (id), \n\tCONSTRAINT fk_artifact_workspace_id_workspace FOREIGN KEY(workspace_id) REFERENCES workspace (id), \n\tCONSTRAINT fk_artifact_execution_id_service_execution FOREIGN KEY(execution_id) REFERENCES service_execution (id), \n\tCONSTRAINT fk_artifact_execution_step_id_execution_step FOREIGN KEY(execution_step_id) REFERENCES execution_step (id)\n)",
'CREATE INDEX ix_artifact_execution ON artifact (execution_id, execution_step_id)',
"CREATE TABLE async_task_run (\n\texecution_id UUID NOT NULL, \n\texecution_step_id UUID NOT NULL, \n\tprovider VARCHAR(128) NOT NULL, \n\texternal_task_id VARCHAR(512) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tnext_poll_at TIMESTAMP WITH TIME ZONE, \n\tpoll_attempts INTEGER NOT NULL, \n\treconcile_deadline TIMESTAMP WITH TIME ZONE, \n\tsubmitted_at TIMESTAMP WITH TIME ZONE, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tresult JSONB, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_async_task_run PRIMARY KEY (id), \n\tCONSTRAINT fk_async_task_run_execution_id_service_execution FOREIGN KEY(execution_id) REFERENCES service_execution (id), \n\tCONSTRAINT fk_async_task_run_execution_step_id_execution_step FOREIGN KEY(execution_step_id) REFERENCES execution_step (id)\n)",
'CREATE INDEX ix_async_task_run_poll ON async_task_run (status, next_poll_at)',
'CREATE UNIQUE INDEX uq_async_task_run_step ON async_task_run (tenant_id, execution_step_id) WHERE is_deleted = false',
"CREATE TABLE channel_delivery (\n\texecution_id UUID NOT NULL, \n\tstep_id UUID, \n\tdelivery_route_id UUID NOT NULL, \n\tchannel_type VARCHAR(64) NOT NULL, \n\tevent_type VARCHAR(64) NOT NULL, \n\tevent_id VARCHAR(128) NOT NULL, \n\tpayload_json JSONB, \n\tstatus VARCHAR(32) NOT NULL, \n\tattempt INTEGER NOT NULL, \n\tmax_attempts INTEGER NOT NULL, \n\tnext_attempt_at TIMESTAMP WITH TIME ZONE, \n\tdispatch_started_epoch INTEGER, \n\tremote_idempotency VARCHAR(256), \n\tdedupe_key VARCHAR(128) NOT NULL, \n\tlast_error TEXT, \n\tdelivered_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tis_deleted BOOLEAN DEFAULT false NOT NULL, \n\tcreate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdate_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttenant_id VARCHAR(128) DEFAULT 'default' NOT NULL, \n\tCONSTRAINT pk_channel_delivery PRIMARY KEY (id), \n\tCONSTRAINT fk_channel_delivery_execution_id_service_execution FOREIGN KEY(execution_id) REFERENCES service_execution (id), \n\tCONSTRAINT fk_channel_delivery_step_id_execution_step FOREIGN KEY(step_id) REFERENCES execution_step (id), \n\tCONSTRAINT fk_channel_delivery_delivery_route_id_channel_delivery_route FOREIGN KEY(delivery_route_id) REFERENCES channel_delivery_route (id)\n)",
'CREATE INDEX ix_channel_delivery_execution ON channel_delivery (execution_id, status)',
'CREATE UNIQUE INDEX uq_channel_delivery_dedupe ON channel_delivery (tenant_id, dedupe_key)',
"INSERT INTO worker_slot_counter (id, tenant_id, is_deleted, create_time, update_time, resource_class, used, slot_limit) SELECT gen_random_uuid(), 'default', false, now(), now(), rc.class, 0, rc.slot_limit FROM (VALUES ('browser', 2), ('external-scan', 2), ('large-report', 1)) AS rc(class, slot_limit) ON CONFLICT (resource_class) DO NOTHING",
]

DOWNGRADE_STATEMENTS = [
'DROP TABLE IF EXISTS "channel_delivery" CASCADE',
'DROP TABLE IF EXISTS "async_task_run" CASCADE',
'DROP TABLE IF EXISTS "artifact" CASCADE',
'DROP TABLE IF EXISTS "task_progress_event" CASCADE',
'DROP TABLE IF EXISTS "execution_step" CASCADE',
'DROP TABLE IF EXISTS "execution_proposal" CASCADE',
'DROP TABLE IF EXISTS "execution_command" CASCADE',
'DROP TABLE IF EXISTS "service_execution" CASCADE',
'DROP TABLE IF EXISTS "execution_snapshot" CASCADE',
'DROP TABLE IF EXISTS "channel_binding" CASCADE',
'DROP TABLE IF EXISTS "bind_code" CASCADE',
'DROP TABLE IF EXISTS "service_release" CASCADE',
'DROP TABLE IF EXISTS "message" CASCADE',
'DROP TABLE IF EXISTS "conversation_run" CASCADE',
'DROP TABLE IF EXISTS "channel_identity" CASCADE',
'DROP TABLE IF EXISTS "channel_delivery_route" CASCADE',
'DROP TABLE IF EXISTS "agent_service_binding" CASCADE',
'DROP TABLE IF EXISTS "skill_artifact_validation_event" CASCADE',
'DROP TABLE IF EXISTS "skill_artifact_capability" CASCADE',
'DROP TABLE IF EXISTS "service_definition" CASCADE',
'DROP TABLE IF EXISTS "conversation" CASCADE',
'DROP TABLE IF EXISTS "channel_account" CASCADE',
'DROP TABLE IF EXISTS "agent_skill_binding" CASCADE',
'DROP TABLE IF EXISTS "agent_knowledge_binding" CASCADE',
'DROP TABLE IF EXISTS "agent_capability_binding" CASCADE',
'DROP TABLE IF EXISTS "agent_access_grant" CASCADE',
'DROP TABLE IF EXISTS "user_project_credential" CASCADE',
'DROP TABLE IF EXISTS "user_memory" CASCADE',
'DROP TABLE IF EXISTS "skill_import_preview" CASCADE',
'DROP TABLE IF EXISTS "skill_artifact" CASCADE',
'DROP TABLE IF EXISTS "channel_command_receipt" CASCADE',
'DROP TABLE IF EXISTS "capability_implementation" CASCADE',
'DROP TABLE IF EXISTS "auth_session" CASCADE',
'DROP TABLE IF EXISTS "audit_log" CASCADE',
'DROP TABLE IF EXISTS "agent_definition" CASCADE',
'DROP TABLE IF EXISTS "workspace" CASCADE',
'DROP TABLE IF EXISTS "worker_slot_counter" CASCADE',
'DROP TABLE IF EXISTS "skill_definition" CASCADE',
'DROP TABLE IF EXISTS "project_platform" CASCADE',
'DROP TABLE IF EXISTS "platform_user" CASCADE',
'DROP TABLE IF EXISTS "model_config" CASCADE',
'DROP TABLE IF EXISTS "knowledge_source" CASCADE',
'DROP TABLE IF EXISTS "capability_definition" CASCADE',
'DROP TABLE IF EXISTS "auth_account" CASCADE',
]

def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)

def downgrade() -> None:
    for statement in DOWNGRADE_STATEMENTS:
        op.execute(statement)
