"""initial schema

Revision ID: 7edbf5dfb136
Revises: 
Create Date: 2026-08-25 07:46:05.785354

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '7edbf5dfb136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('publish_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('idx_audit_target', 'audit_logs', ['tenant_id', 'target_type', 'target_id', 'created_at'], unique=False)
    op.create_table('bind_codes',
    sa.Column('bind_code_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bind_code_id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index('idx_bind_code_tenant_expiry', 'bind_codes', ['tenant_id', 'expires_at'], unique=False)
    op.create_table('channel_identities',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('channel_type', sa.String(length=64), nullable=False),
    sa.Column('channel_user_id', sa.String(length=255), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'channel_type', 'channel_user_id')
    )
    op.create_index('idx_channel_identity_platform_user', 'channel_identities', ['tenant_id', 'platform_user_id'], unique=False)
    op.create_table('chat_access_tokens',
    sa.Column('access_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=False),
    sa.Column('runtime_profile_id', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('access_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_chat_access_user', 'chat_access_tokens', ['tenant_id', 'platform_user_id', 'revoked_at'], unique=False)
    op.create_table('config_revisions',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('outbox_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_outbox_dispatch', 'outbox_events', ['status', 'available_at', 'created_at'], unique=False)
    op.create_table('platform_users',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'platform_user_id')
    )
    op.create_table('publish_records',
    sa.Column('publish_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('publish_note', sa.String(length=1000), nullable=True),
    sa.Column('approval_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('publish_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_publish_record_resource', 'publish_records', ['tenant_id', 'resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_table('resource_bindings',
    sa.Column('binding_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_version_selector', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('credential_ref', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('binding_id')
    )
    op.create_index('idx_binding_subject', 'resource_bindings', ['tenant_id', 'subject_type', 'subject_id', 'resource_type', 'enabled'], unique=False)
    op.create_table('resource_definitions',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', 'kind', 'resource_id', 'version')
    )
    op.create_index('idx_resource_latest_published', 'resource_definitions', ['tenant_id', 'kind', 'resource_id', 'status', 'published_at'], unique=False)
    op.create_table('session_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_l1', 'session_memory', ['tenant_id', 'session_id', 'level', 'id'], unique=False)
    op.create_index('idx_memory_l2', 'session_memory', ['tenant_id', 'user_id', 'level', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memory_l2', table_name='session_memory')
    op.drop_index('idx_memory_l1', table_name='session_memory')
    op.drop_table('session_memory')
    op.drop_index('idx_resource_latest_published', table_name='resource_definitions')
    op.drop_table('resource_definitions')
    op.drop_index('idx_binding_subject', table_name='resource_bindings')
    op.drop_table('resource_bindings')
    op.drop_index('idx_publish_record_resource', table_name='publish_records')
    op.drop_table('publish_records')
    op.drop_table('platform_users')
    op.drop_index('idx_outbox_dispatch', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('config_revisions')
    op.drop_index('idx_chat_access_user', table_name='chat_access_tokens')
    op.drop_table('chat_access_tokens')
    op.drop_index('idx_channel_identity_platform_user', table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_index('idx_bind_code_tenant_expiry', table_name='bind_codes')
    op.drop_table('bind_codes')
    op.drop_index('idx_audit_target', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
