"""phase2-6 schema drift: secret/artifact/durable/memory/workflow_run/trace/approval/eval/migration tables

Revision ID: e5189f5b1ed1
Revises: f7a3c91d2e84
Create Date: 2026-08-30 11:49:42.521818

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e5189f5b1ed1'
down_revision = 'f7a3c91d2e84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_records',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('approval_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('target_version', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('requester_actor_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approver_actor_id', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', 'approval_id')
    )
    op.create_table('artifact_metadata',
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('owner_type', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('execution_id', sa.String(length=128), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('retention_policy', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index('idx_artifact_tenant_ns_key', 'artifact_metadata', ['tenant_id', 'namespace', 'key'], unique=False)
    op.create_table('durable_task',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('idx_durable_task_status_claimed', 'durable_task', ['status', 'claimed_at'], unique=False)
    op.create_table('eval_runs',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('eval_set_id', sa.String(length=255), nullable=False),
    sa.Column('eval_set_version', sa.String(length=64), nullable=False),
    sa.Column('runtime_profile_id', sa.String(length=255), nullable=False),
    sa.Column('runtime_profile_version', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('execution_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'run_id')
    )
    op.create_table('migration_records',
    sa.Column('migration_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('shadow_row_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('migration_id')
    )
    op.create_table('personal_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('memory_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('source_session_id', sa.String(length=128), nullable=False),
    sa.Column('source_range_hash', sa.String(length=64), nullable=True),
    sa.Column('learning_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_personal_memory_user', 'personal_memory', ['tenant_id', 'user_id', 'id'], unique=False)
    op.create_table('profile_attributes',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=4096), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_explicit', sa.Boolean(), nullable=False),
    sa.Column('user_editable', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.String(length=64), nullable=True),
    sa.Column('valid_until', sa.String(length=64), nullable=True),
    sa.Column('superseded_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'platform_user_id', 'key')
    )
    op.create_index('idx_profile_attributes_user', 'profile_attributes', ['tenant_id', 'platform_user_id'], unique=False)
    op.create_table('secret_credentials',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('ref', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('cipher_version', sa.String(length=64), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'ref')
    )
    op.create_index('idx_secret_tenant_name', 'secret_credentials', ['tenant_id', 'name'], unique=False)
    op.create_table('secret_master_keys',
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('trace_records',
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('runtime_profile_id', sa.String(length=255), nullable=False),
    sa.Column('runtime_profile_version', sa.String(length=64), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('events_json', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_json', sa.JSON(), nullable=True),
    sa.Column('tools_json', sa.JSON(), nullable=True),
    sa.Column('hooks_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index('idx_trace_tenant_execution', 'trace_records', ['tenant_id', 'execution_id'], unique=False)
    op.create_table('workflow_run',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=512), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('node_states', sa.JSON(), nullable=True),
    sa.Column('pinned_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'run_id')
    )
    op.create_index('idx_wf_run_exec', 'workflow_run', ['execution_id'], unique=False)
    op.create_index('idx_wf_run_tenant', 'workflow_run', ['tenant_id'], unique=False)
    op.add_column('audit_logs', sa.Column('trace_id', sa.String(length=128), nullable=True))
    op.create_index('idx_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.add_column('capability_grants', sa.Column('capability_kind', sa.String(length=16), server_default='skill', nullable=False))
    op.create_index('idx_binding_tenant_created', 'resource_bindings', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_binding_tenant_created', table_name='resource_bindings')
    op.drop_column('capability_grants', 'capability_kind')
    op.drop_index('idx_audit_tenant_created', table_name='audit_logs')
    op.drop_column('audit_logs', 'trace_id')
    op.drop_index('idx_wf_run_tenant', table_name='workflow_run')
    op.drop_index('idx_wf_run_exec', table_name='workflow_run')
    op.drop_table('workflow_run')
    op.drop_index('idx_trace_tenant_execution', table_name='trace_records')
    op.drop_table('trace_records')
    op.drop_table('secret_master_keys')
    op.drop_index('idx_secret_tenant_name', table_name='secret_credentials')
    op.drop_table('secret_credentials')
    op.drop_index('idx_profile_attributes_user', table_name='profile_attributes')
    op.drop_table('profile_attributes')
    op.drop_index('idx_personal_memory_user', table_name='personal_memory')
    op.drop_table('personal_memory')
    op.drop_table('migration_records')
    op.drop_table('eval_runs')
    op.drop_index('idx_durable_task_status_claimed', table_name='durable_task')
    op.drop_table('durable_task')
    op.drop_index('idx_artifact_tenant_ns_key', table_name='artifact_metadata')
    op.drop_table('artifact_metadata')
    op.drop_table('approval_records')
    # ### end Alembic commands ###
